package webdriver.utils;

public enum WebDriverType 
{
	CHROME,
	FIREFOX,
	IE,
	EDGE,
	EDGE_LEGACY,
	GRID_CHROME,
	GRID_FIREFOX,
	GRID_MICROSOFTEDGE,
	GRID_INTERNETEXPLORER,
	DOCKER_GRID_LOCAL,
	DOCKER_GRID_CHROME,
	DOCKER_GRID_FIREFOX,
	GRID_CHROME_WINDOWS10,
	BROWSER_STACK_EDGE,
    BROWSER_STACK_IE11,
    BROWSER_STACK_CHROME,
	DOCKER_GRID_CHROME_HEADLESS
}
